# ghactions-angular-project - Test Angular project

name: ghactions-angular-project-github-pages-deploy

on:
  push:
    branches: [ "master", "memlab-ci" ]
  pull_request:
    branches: [ "master", "memlab-ci" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  my_build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Angular app
        run: |
          npm install
          npm run build-gh-pages

      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload new gh-pages bundle from ./dist folder
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist/ghactions-angular-project'
      - name: Deploy to GitHub Pages # https://kievsash.github.io/ghactions-angular-project/
        id: deployment
        uses: actions/deploy-pages@main

      - name: Download previous run number of leaks artifact
        uses: dawidd6/action-download-artifact@master
        with:
          workflow: gh-pages-deploy.yml
          if_no_artifact_found: warn
          name: my-leaks
          github_token: ${{ github.token }}

      - name: Check leak file
        run: |
          ls -la ./my-leaks
          cat ./my-leaks

      - name: Run memlab scenario and comparing leaks number
        continue-on-error: true
        run: node ./memlab/check-leaks.js

      - name: Just display files
        continue-on-error: true
        run: ls -la ./ && ls -la ./memlab && cat ./my-leaks && cat ./memlab/my-leaks

      - name: Upload memlab results
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: my-leaks
          path: ./memlab/my-leaks


