# ghactions-angular-project - Test Angular project

name: ghactions-angular-project-s3-deploy-pipeline
env:
  S3_BUCKET_NAME: "my-deployed-s3"
  APP_NAME: "My angular app"
  ENVIRONMENT_NAME: "Production"
  DEPLOY_PACKAGE_NAME: "angular_app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "us-east-1"
on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  my_s3_deploy_ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build-s3

    - name: zip-files
      run: |
        zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./dist/ghactions-angular-project
        ls -la ${{ env.DEPLOY_PACKAGE_NAME }}

    - name: Configure AWS creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }} # you get it while creating aws IAM user with S3Access policy
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }} # same here
        aws-region: ${{ env.AWS_REGION_NAME }}

    - name: Copy deployment package to S3 bucket
      run: aws s3 cp ./dist/ghactions-angular-project s3://${{ env.S3_BUCKET_NAME }} --recursive
      # http://my-deployed-s3.s3-website-us-east-1.amazonaws.com/ - but I my shutdown it soon

